on:
  workflow_call:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installing Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org/'
      - run: |
          git fetch origin main
          git checkout main
      - name: Installing dependencies
        run: npm install
      - name: Compile source
        run: npm run build
      - name: "NPM Identity"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - name: Publish source
        run: |
          npx lerna publish from-package --no-private --no-verify-access --registry https://registry.npmjs.org/ --yes
        env:
          npm_config__auth: '${{ secrets.NPM_TOKEN }}'
