name: Lint code & compile test

on:
  workflow_call:
    inputs:
      SETUP_PNPM:
        description: "Docker image platforms"
        type: boolean
        required: false
        default: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
    - name: Setup pnpm
      uses: pnpm/action-setup@v4 # v2.4.0
      with:
        version: latest
    - name: Setup Node.js
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
      with:
        node-version-file: .node-version

    - name: Installing dependencies
      run: pnpm install --frozen-lockfile
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Lint code
      run: pnpm run lint

  compile:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

    - name: Setup pnpm
      if: ${{ inputs.SETUP_PNPM }}
      uses: pnpm/action-setup@v4 # v2.4.0
      with:
        version: latest
  
    - name: Setup Node.js
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
      with:
        node-version-file: .node-version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Installing dependencies
      run: pnpm install --frozen-lockfile
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Test compile
      run: pnpm run build
