name: Lint code & compile test

on:
  workflow_call:

jobs:
  lint-compile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
    - name: Setup Node.js
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
      with:
        node-version-file: .node-version
    - name: Install dependencies
      run: npm ci
    - name: Test compile
      run: npm run build
    - name: Lint code
      run: npm run lint
